config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/about' => 'static_pages#about'
  get '/help' => 'static_pages#help'
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'following/:id' => 'follows#following'
  get 'followed/:id' => 'follows#followed'
  get 'search' => 'posts#search'

  resources :users
  resources :posts
  resources :likes, only: [:update, :destroy]
  resources :follows, only: [:update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
  validates_uniqueness_of :follower_id, scope: :followed_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  mount_uploader :file, UploadPdffileUploader

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 200 }
  # validates :file, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validate  :pdf_size

  private

    def pdf_size
      if file.size > 5.megabytes
        flash[:danger] = "ファイルサイズを５MBより小さくしてください"
      end
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_follows, class_name: "Follow",
                           foreign_key: "follower_id",
                           dependent: :destroy
  has_many :following, through: :active_follows, source: :followed
  has_many :passive_follows, class_name: "Follow",
                            foreign_key: "followed_id",
                            dependent: :destroy
  has_many :followers, through: :passive_follows, source: :follower

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, presence: true, allow_nil: true

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_follows.find_by(followed_id: other_user.id).destroy
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  
  before_action :logged_in_user, only: [:update, :destroy]

  def followed
    @title = "フォロワー"
    @user = User.find(params[:id])
    @follows = @user.followers
    render 'follows/index'
  end

  def following
    @title = "フォロー"
    @user = User.find(params[:id])
    @follows = @user.following
    render 'follows/index'
  end
  
  def update
    follow = current_user.active_follows.build(followed_id: params[:id])
    follow.save
    redirect_to request.referer
  end

  def destroy
    follow = current_user.active_follows.find_by(followed_id: params[:id])
    follow.delete
    redirect_to request.referer
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :logged_in_user

  def update
    # ユーザーと投稿に紐づけてlikeを生成
    like = current_user.likes.build(post_id: params[:id])
    like.save
    # 直前のリクエストを参照
    redirect_to request.referer
  end

  def destroy
    like = current_user.likes.find_by(post_id: params[:id])
    like.delete
    # 直前のリクエストを参照
    redirect_to request.referer
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = current_user.posts.build if logged_in?
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
  end

  def create
    # 関連付けを行ったので、Userオブジェクトに対してpostを呼び出す
    @post = current_user.posts.build(post_params)
    
    if @post.save
      flash[:success] = "投稿しました"
      redirect_to post_path(@post)
    else
      render 'new'
    end

  end

  def search
    # 検索文を変数に代入
    content = params[:search]

    if content
      @posts = Post.where("title LIKE ?", "%#{content}%")
    else
      @posts = Post.all
    end
    
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :file)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to root_url
    else
      flash.now[:danger] = "入力された情報に誤りがあります"
      # userインスタンスを初期化
      @user = User.new
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :confirm_valid_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def show
    @user = User.find(params[:id])
    @feed_items = @user.posts.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      log_in(@user)
      flash[:success] = "スコアーズへようこそ！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to @user
    else
      render 'edit'
    end

  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url
  end

  # ユーザー本人であるかを確かめ、違う場合ホームへ飛ばす
  def confirm_valid_user
    @user = User.find(params[:id])
    unless @user == current_user
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end

  # 管理者権限を持っているか確認する
  def admin_user
    unless current_user.admin?
      redirect_to root_url
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper

  def already_following?(user)
      current_user.active_follows.exists?(followed_id: user.id)
  end

  def render_follow(user)
    if already_following?(user) 
      render 'follows/follow'
    else 
      render 'follows/unfollow'
    end
  end

end

app/helpers/likes_helper.rb
module LikesHelper

  def already_liked?(post)
    current_user.likes.exists?(post_id: post.id)
  end

  def render_likes(post)
    if already_liked?(post)
      render 'likes/unlike', { post: post } 
    else 
      render 'likes/like', { post: post } 
    end 
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    # sessionというハッシュの:user_idキーにuser.idを代入するイメージ
    session[:user_id] = user.id
  end

  # 現在のユーザーを取得するメソッド
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # あるユーザーが現在ログインしているユーザーかどうか真偽値で返すメソッド
  def current_user?(user)
    current_user == user
  end

  # loginしていればtrue,していなければfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # logoutの処理
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # loginしていなければログインフォームへ飛ばす
  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインが必要です"
      redirect_to login_url
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/follows/_follow.html.erb
<%# followされている状態のview %>
<div class="follow btn btn-secondary">
  <%= link_to "フォローを外す", follow_path(@user), method: :delete %>
</div>

app/views/follows/_unfollow.html.erb
<%# followされていない状態のview %>
<div class="unfollow btn btn-primary">
  <%= link_to "フォロー", follow_path(@user), method: :patch %>
</div>

app/views/follows/index.html.erb
<% provide(:page_title, "#{@user.name}のフォロワー") %>

<div class="index_main">
  <div class="float_front">
    <%= render 'layouts/header' %>
    <div class="index_title">
      <h1><%= @title %></h1>
    </div>

    <% @follows.each do |follow| %>
      <ul class="user_profile">
        <li>
            <%= gravatar_for follow %>
            <%= link_to follow.name, follow, class: "user_name user_list" %>
        </li>
      </ul>
    <% end %>

  </div>
</div>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <%= render 'shared/login_user_header' %>
<% else %>
  <%= render 'shared/not_login_user_header' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %></title>
    <%= csrf_meta_tags %>

    <%# font-awesomeの導入 %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%# bootstrapを先に読み込む %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
    crossorigin="anonymous">
    <%# custom.scss の読み込み %>
    <%= stylesheet_link_tag    'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%# flashの描画 %>
    <%= render 'shared/flash' %> 
    <%# 各ファイルの内容を描画 %>
    <%= yield %>
    <div class="debug">
      <%= debug(params) if Rails.env.development? %>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" 
    integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" 
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" 
    integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" 
    crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/_like.html.erb
<div class="unlikes_info">
  <%= link_to like_path(post), method: :patch do %>
    <i class="far fa-heart like-btn"></i>
  <% end %>
  <%= post.likes.count %>
</div>

app/views/likes/_unlike.html.erb
<div class="likes_info">
  <%= link_to like_path(post), method: :delete do %>
    <i class="far fa-heart unlike-btn"></i>
  <% end %>
  <%= post.likes.count %>
</div>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<% provide(:page_title, "新規投稿") %>
<%# formを送信するurlの指定 %>
<% provide(:form_url, posts_path) %>
<% provide(:method, :post) %>

<div class="signup_main">
  <div class="float_front">
    <%= render "layouts/header" %>
    <%= render 'shared/error_messages', { object: @post }%>
    <div class="signup_container">
      <h1 class="signup_title">新規投稿</h1>
      <%= render 'shared/post_form' %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<% provide(:page_title, "検索結果") %>

<div class="index_main">
  <div class="float_front">
    <%= render "layouts/header" %>
    <div class="index_title">
      <h1>検索結果</h1>
    </div>
    <div class="search_form">
      <h1>Connect pianist to scores!<h1>
      <p>-あなたの弾きたい！が見つかる-</p>
      <div class="search_box">
        <%= form_tag(search_path, method: :get) do %>
          <%= label_tag :楽譜検索 %>
          <%= text_field_tag :search %>
          <%= submit_tag "検索", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <% if !@posts.exists? %>
    <% flash[:success] = "該当する結果はありません" %>
    <% else %>
      <% @posts.each do |post| %>
        <ul class="user_profile">
          <li>
              <%= gravatar_for post.user %>
              <%= link_to post.user.name, user_path(post.user) %>
              <%= link_to post.title, post, class: "user_name user_list" %>          
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:page_title, "#{@post.user.name}") %>

<div class="show_main">
  <div class="float_front">
    <%= render "layouts/header" %>
    <div class="post_profile">
     <div class="pdf_thumbnail">
        <object data="<%= @post.file.url %>" type="application/pdf" width="200" height="300"></object>
        <%# ログイン済みユーザーにのみ、楽譜の表示を行う %>
        <% if current_user != nil %>
        <%= link_to "pdfを表示", @post.file.url, target: :_blank, class: "pdf_link" %>
        <% end %>
     </div>
     <div class="pdf_info">
       <div class="info_container">
         <div class="pdf_title">
           <h1>楽譜のタイトル</h1>
           <h1><%= @post.title %></h1>
         </div>
         <%# ログインしていれば、いいねを描画する %>
         <% if current_user != nil %>
          <%= render_likes(@post) %>
         <% end %>
         <div class="date_info">
           <p>投稿者： <%= link_to @post.user.name, user_path(@post.user) %></p>
           <p>投稿日： <%= @post.created_at.strftime('%Y/%m/%d') %></p>
           <p>最終更新日： <%= @post.updated_at.strftime('%Y/%m/%d') %></p>
         </div>
       </div>
       <div class="pdf_detail">
         <p>楽譜説明</p>
         <div class="pdf_text_box">
           <p><%= @post.content %></p>
         </div>
       </div>
     </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div class="errors">
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |message_type, message| %>
  <div class="flash_wrapper">
    <div class="alert_<%= message_type %>"><%= message %></div>
  </div>
  <% end %>
<% end %>

app/views/shared/_login_user_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-info">
    <div class="collapse navbar-collapse" id="navmenu">
      <%# 左寄せ %>
      <%# <div class="navbar-left"> %>
        <ul class="navbar-nav navbar-left">
          <li class="nav-item nav-link"><%= link_to "スコアーズ", root_path %></li>
        </ul>
      <%# </div> %>
      <%# 右寄せ %>
      <%# <div class="navbar-right"> %>
        <ul class="navbar-nav navbar-right">
          <li class="nav-item nav-link active"><%= link_to "このサイトについて", about_path %></li>
          <li class="nav-item nav-link active"><%= link_to "ヘルプ", help_path %></li>
          <li class="nav-item nav-link active"><%= link_to "ユーザーリスト", users_path %></li>
          <li class="nav-item nav-link active"><%= link_to "新規投稿", new_post_path %></li>
          <li class="nav-item nav-link active"><%= link_to current_user.name, user_path(current_user) %></li>
          <li class="nav-item nav-link active"><%= link_to "ユーザー設定", edit_user_path(current_user) %></li>
          <li class="nav-item nav-link active"><%= link_to "ログアウト", logout_path, method: :delete %></li>
          <%# dropdownが実装できないのでいったん保留 %>
        <% if false %>
          <li class="nav-item nav-link active">
              <div class="navbar-nav dropdown">
                <a class="nav-item nav-link dropdown-toggle active" href="<%= user_url(current_user) %>"　
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.name %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenulink">
                  <%= link_to "ユーザー設定", "#", class: "dropdown-item" %>
                  <%= link_to "ログアウト", logout_path, class: "dropdown-item" %>
                </div>
              </div>
          </li>
        <% end %>
          <%# ここまで %>
          </li>
        </ul>
      <%# </div> %>
    </div>
  </nav>

app/views/shared/_not_login_user_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-info">
    <div class="collapse navbar-collapse" id="navmenu">
      <%# 左寄せ %>
        <ul class="navbar-nav navbar-left">
          <li class="nav-item nav-link navbar-brand"><%= link_to "スコアーズ", root_path %></li>
        </ul>
      <%# 右寄せ %>
        <ul class="navbar-nav navbar-right">
          <li class="nav-item nav-link active"><%= link_to "このサイトについて", about_path %></li>
          <li class="nav-item nav-link active"><%= link_to "ヘルプ", help_path %></li>
          <li class="nav-item nav-link active"><%= link_to "ユーザーリスト", users_path %></li>
          <li class="nav-item nav-link active"><%= link_to "新規登録", signup_path %>
          <li class="nav-item nav-link active"><%= link_to "ログイン", login_path %>
          </li>
        </ul>
    </div>
  </nav>

app/views/shared/_post_form.html.erb
  <%= form_with model: @post, url: yield(:form_url), method: yield(:method),
  local: true, multipart: true do |form| %>
  
    <div class="form-group form-group-md row justify-content-center">
      <%= form.label :title, "タイトル", class: "control-label" %>
      <div class="col-md-5">
        <%= form.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %>
      </div>
    </div>
    <div class="form-group form-group-md row justify-content-center">
      <%= form.label :content, "説明文" , class: "control-label" %>
      <div class="col-md-5">
        <%= form.text_area :content, class: "form-control ", placeholder: "楽譜の説明を入力してください" %>
      </div>
    </div>
    <div class="form-group form-group-md row justify-content-center">
      <%= form.label :file, "pdfファイル", class: "control-label" %>
      <div class="custom-file col-md-5">
        <%= form.file_field :file, class: "custom-file-input" %>
        <%= form.label :file, "ファイルを選択してください", class: "custom-file-label" %>
      </div>
    </div>
    <%= form.submit "投稿", class: "btn btn-primary" %>

  <% end %>

app/views/shared/_user_form.html.erb
<%= form_with model: @user, url: yield(:form_url), method: yield(:method), local: true do |form| %>
  
  <div class="form-group form-group-md row justify-content-center">
    <%= form.label :name, "名前", class: "control-label" %>
    <div class="col-md-5">
      <%= form.text_field :name, class: "form-control", placeholder: "名前を入力してください" %>
    </div>
  </div>
  <div class="form-group form-group-md row justify-content-center">
    <%= form.label :email, "メール" , class: "control-label" %>
    <div class="col-md-5">
      <%= form.text_field :email, class: "form-control ", placeholder: "メールを入力してください" %>
    </div>
  </div>
  <div class="form-group form-group-md row justify-content-center">
    <%= form.label :password, "パスワード", class: "control-label" %>
    <div class="col-md-5">
      <%= form.password_field :password, class: "form-control", 
      placeholder: "パスワードを入力してください" %>
    </div>
  </div>
  <div class="form-group form-group-md row justify-content-center">
    <%= form.label :password_confirmation, "パスワードの確認", class: "control-label" %>
    <div class="col-md-5">
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <%= form.submit "登録", class: "btn btn-primary" %>

<% end %>

app/views/static_pages/about.html.erb
<%= provide(:page_title, 'サイト詳細') %>

<main>
  <div class="float_front">
    <%= render 'layouts/header' %>
    <div class="help_container">
      <h1>使いかた</h1>
      <ul class="help_list">
        <li>使い方</li>
        <li>使い方</li>
        <li>使い方</li>
        <li>使い方</li>
        <li>使い方</li>
      </ul>
    </div>
  </div>
</main>

app/views/static_pages/help.html.erb
<% provide(:page_title, 'ヘルプ') %>

<main>
  <div class="float_front">
    <%= render 'layouts/header' %>
    <div class="help_container">
      <h1>ヘルプ</h1>
      <ul class="help_list">
        <li>助けます</li>
        <li>助けます</li>
        <li>助けます</li>
        <li>助けます</li>
        <li>助けます</li>
      </ul>
    </div>
  </div>
</main>

app/views/static_pages/home.html.erb
<% provide(:page_title, 'ホーム') %>

<main>
  <div class="float_front">
    <%# headerの描画 %>
    <%= render 'layouts/header' %>

    <div class="search_form">
      <h1>Connect pianist to scores!<h1>
      <p>-あなたの弾きたい！が見つかる-</p>
      <div class="search_box">
        <%= form_tag(search_path, method: :get) do %>
          <%= label_tag :楽譜検索 %>
          <%= text_field_tag :search %>
          <%= submit_tag "検索", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="search_box">
        <p>ログイン時、以下のサンプルユーザーが使えます</p>
        <p>サンプルユーザー</p>
        <p>名前：　サンプルくん</p>
        <p>メール：　sample@gmail.com</p>
        <p>パスワード：　sample</p>
      </div>
  </div>
</main>

app/views/users/edit.html.erb
<% provide(:page_title, "ユーザー更新") %>
<% provide(:form_url, user_path) %>
<% provide(:method, :patch) %>

<div class="signup_main">
  <div class="float_front">
    <%= render "layouts/header" %>
    <%= render 'shared/error_messages', { object: @user } %>
    <div class="signup_container">
      <h1 class="signup_title">ユーザー更新</h1>
      <%= render 'shared/user_form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:page_title, "ユーザーリスト") %>

<div class="index_main">
  <div class="float_front">
    <%= render "layouts/header" %>
    <div class="index_title">
      <h1>ユーザーリスト</h1>
    </div>

    <%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

    <% @users.each do |user| %>
    <ul class="user_profile">
      <li>
          <%= gravatar_for user %>
          <%= link_to user.name, user, class: "user_name user_list" %>
          <%# user削除用リンクの作成、管理者だけに表示. ただし、管理者自身の削除リンクは表示しない %>
          <% if current_user != nil && current_user.admin? && !current_user?(user) %>
          <%= link_to "削除", user, method: :delete, data: { confirm: "本当に削除してもよろしいですか？" } %>
          <% end %>
      </li>
    </ul>
    <% end %>

    <%= will_paginate @users, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:page_title, "新規登録") %>
<%# formを送信するurlの指定 %>
<% provide(:form_url, signup_path) %>
<% provide(:method, :post) %>

<div class="signup_main">
  <div class="float_front">
    <%= render "layouts/header" %>
    <%= render 'shared/error_messages', { object: @user } %>
    <div class="signup_container">
      <h1 class="signup_title">新規登録</h1>
      <%= render 'shared/user_form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:page_title, "#{@user.name}") %>

<div class="show_main">
  <div class="float_front">
    <%= render "layouts/header" %>
    <div class="user_profile">
        <%= gravatar_for @user %>
        <div class="user_info">
          <h1><%= link_to @user.name, @user, class: "user_name" %></h1>
          <%# ログイン済み、かつ他のユーザーの詳細ページのとき、followボタンを表示 %>
          <% if current_user != nil && @user != current_user %>
          <%= render_follow(@user) %>
          <% end %>
          <div class="follow_info">
            <%= link_to "フォロワー: #{@user.passive_follows.count}", "/followed/#{@user.id}" %>
            <%= link_to "フォロー: #{@user.active_follows.count}", "/following/#{@user.id}" %>
          </div>
        </div>
        <%# userに紐づいたpostsを表示 %>
        <% if @feed_items.any? %>
          <div class="feed">
            <ol class="posts">
              <% @feed_items.each do |feed| %>
                <div class="post_profile">
                  <div class="pdf_thumbnail">
                    <object data="<%= feed.file.url %>" type="application/pdf" 
                    width="100" height="150"></object>
                    <%= link_to "pdfへのリンク", feed.file.url, target: :_blank, class: "pdf_link" %>
                  </div>
                  <div class="feed_info">
                    <p>楽譜のタイトル：　<%= link_to feed.title, post_path(feed) %></p>
                    <%# ログイン済みなら、いいね表示 %>
                    <% if current_user != nil %>
                    <%= render_likes(feed) %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </ol>
            <%= will_paginate @feed_items, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
          </div>
        <% end %>
    </div>
  </div>
</div>